name: Validate Homey App

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Homey app manifest
        run: bun prepare

      - name: Validate Homey App
        run: npx homey app validate --level verified
